language: objective-c  
osx_image: xcode7.2
xcode_project: Birthdays.xcodeproj 
xcode_scheme: Birthdays 
xcode_sdk: iphonesimulator9.2

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 52ebf1b4-fdea-4cd6-9273-514c4d3af8d5
  - find / -name '*.profdata'