language: objective-c  
osx_image: xcode7.2
xcode_project: Birthdays.xcodeproj 
xcode_scheme: Birthdays 
xcode_sdk: iphonesimulator9.2
before_install:
  - pip install codecov
after_success:
  - codecov